In [1]:
import plotly.io as pio
pio.renderers.default = 'iframe'

In [2]:
import os
import pandas as pd

base_path = '../data/results/gridsearch'

results = []
paths = os.listdir(base_path)
for path in paths:
    results.append(pd.read_csv(os.path.join(base_path, path)))
results = pd.concat(results, ignore_index=True)
results

,Unnamed: 0,subject,dataset,fold,theta,n_blocks,train_score,test_score,train_mse,test_mse
0,0,2,BNCI2014-008,0,1.0,1,0.874615,0.829714,5.744999e-31,6.968829e-31
1,1,2,BNCI2014-008,0,1.0,2,0.900888,0.844898,0.000000e+00,0.000000e+00
2,2,2,BNCI2014-008,0,1.0,3,0.919202,0.856816,0.000000e+00,0.000000e+00
3,3,2,BNCI2014-008,1,1.0,1,0.873351,0.780408,4.625844e-31,4.676566e-31
4,4,2,BNCI2014-008,1,1.0,2,0.901974,0.782204,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...
51675,635,2,BNCI2014-008,19,0.9,28,0.869052,0.834449,4.075444e-01,5.469961e-01
51676,636,2,BNCI2014-008,19,0.9,29,0.880446,0.848163,3.582450e-01,4.677487e-01
51677,637,2,BNCI2014-008,19,0.9,30,0.881577,0.849796,3.409768e-01,4.434790e-01
51678,638,2,BNCI2014-008,19,0.9,31,0.881994,0.850939,3.333991e-01,4.297670e-01
51679,639,2,BNCI2014-008,19,0.9,32,0.882686,0.852408,3.259847e-01,4.128338e-01

In [3]:
import plotly.express as px

df = results.copy()
idx = ['dataset', 'subject', 'fold', 'theta']
df = df.set_index(idx, drop=True)
df = df.sort_index()
first_block = df[df.n_blocks == 1]
metrics = ['train_score', 'test_score', 'train_mse', 'test_mse']
df[[m+'_diff' for m in metrics]] = df[metrics]-first_block[metrics]
df = df.reset_index()
df

,dataset,subject,fold,theta,Unnamed: 0,n_blocks,train_score,test_score,train_mse,test_mse,train_score_diff,test_score_diff,train_mse_diff,test_mse_diff
0,BNCI2014-008,1,0,0.0,0,1,0.513741,0.538286,9.988982e-01,1.017816e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
1,BNCI2014-008,1,0,0.0,1,2,0.831383,0.755755,9.976351e-01,1.015496e+00,0.317642,0.217469,-1.263076e-03,-2.320026e-03
2,BNCI2014-008,1,0,0.0,2,3,0.831303,0.753633,9.969584e-01,1.015501e+00,0.317562,0.215347,-1.939715e-03,-2.314799e-03
3,BNCI2014-008,1,0,0.0,3,4,0.853630,0.794776,9.960482e-01,1.014789e+00,0.339889,0.256490,-2.849983e-03,-3.027455e-03
4,BNCI2014-008,1,0,0.0,4,5,0.865109,0.775837,9.941280e-01,1.014911e+00,0.351369,0.237551,-4.770174e-03,-2.905116e-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51675,BNCI2014-008,8,19,0.9,638,31,0.970434,0.928980,3.843097e-01,4.094076e-01,0.040054,0.007510,-5.159167e-01,-4.861958e-01
51676,BNCI2014-008,8,19,0.9,639,32,0.970509,0.929633,3.703387e-01,3.956329e-01,0.040129,0.008163,-5.298878e-01,-4.999704e-01
51677,BNCI2014-008,8,19,1.0,57,1,0.968187,0.920000,5.668691e-31,5.668399e-31,0.000000,0.000000,0.000000e+00,0.000000e+00
51678,BNCI2014-008,8,19,1.0,58,2,0.976608,0.922939,0.000000e+00,0.000000e+00,0.008421,0.002939,-5.668691e-31,-5.668399e-31
51679,BNCI2014-008,8,19,1.0,59,3,0.982452,0.907102,0.000000e+00,0.000000e+00,0.014265,-0.012898,-5.668691e-31,-5.668399e-31

In [4]:
df= df.query('subject==2')
df = df.groupby(['n_blocks', 'theta'])['test_score'].aggregate('mean').reset_index()
n_colors = df['theta'].nunique()
colors = px.colors.sample_colorscale("viridis", [n/(n_colors -1) for n in range(n_colors)])
fig = px.line(df, x='n_blocks', y='test_score', color='theta', color_discrete_sequence=colors)
fig.show()

In [5]:
import seaborn as sns
import matplotlib.pyplot as plt

thetas = [0, 0.1, 1]
df = results[results['theta'].isin(thetas)].copy()
sns.lineplot(df, x='n_blocks', y='test_score', hue='theta', errorbar='ci')
plt.show()

In [6]:
results.to_csv('gridsearch_erp.csv')

In [7]:
df = results.copy()
df = df.groupby(['n_blocks', 'theta'])['test_score'].agg('mean')
df = df.reset_index()
df = df.pivot( columns='n_blocks', index='theta', values='test_score')
df

n_blocks,1,2,3,4,5,6,7,8,9,10,...,23,24,25,26,27,28,29,30,31,32
theta,,,,,,,,,,,,,,,,,,,,,
0.0,0.829823,0.850261,0.857993,0.858551,0.860212,0.859565,0.860018,0.860474,0.860434,0.859650,...,0.858886,0.858728,0.858819,0.858767,0.858912,0.859085,0.859133,0.859113,0.859254,0.859272
0.1,0.831645,0.850061,0.857212,0.860684,0.861036,0.861533,0.863204,0.863278,0.864111,0.864088,...,0.863947,0.863787,0.863501,0.863649,0.863486,0.863591,0.863477,0.863520,0.863539,0.863456
0.2,0.825633,0.846953,0.850359,0.854246,0.853911,0.856548,0.858244,0.861648,0.862219,0.862766,...,0.862463,0.862530,0.862527,0.862787,0.862668,0.862599,0.862548,0.862486,0.862419,0.862096
0.3,0.809440,0.840590,0.846211,0.848031,0.847597,0.848187,0.849597,0.850265,0.853908,0.854920,...,0.860417,0.860254,0.860666,0.860616,0.860428,0.860512,0.860535,0.860465,0.860792,0.860900
0.4,0.796907,0.825653,0.837644,0.841326,0.842606,0.846809,0.847427,0.847786,0.848084,0.848151,...,0.855767,0.855564,0.856078,0.856145,0.856200,0.856297,0.856758,0.856961,0.857224,0.857193
0.5,0.782317,0.811545,0.828199,0.833209,0.836701,0.838759,0.841529,0.842636,0.843299,0.843513,...,0.850606,0.850589,0.850514,0.850486,0.850834,0.851230,0.851405,0.851413,0.851639,0.852303
0.6,0.770143,0.794304,0.812262,0.819083,0.823345,0.827376,0.830417,0.832671,0.834448,0.836017,...,0.846620,0.846876,0.846992,0.847129,0.847102,0.847061,0.847053,0.847018,0.847198,0.847252
0.7,0.760749,0.787415,0.798899,0.804097,0.809452,0.813776,0.816882,0.819763,0.822251,0.825213,...,0.842063,0.842344,0.843012,0.843263,0.843546,0.843905,0.843870,0.844189,0.844197,0.844645
0.8,0.747508,0.775750,0.787543,0.796754,0.802648,0.807412,0.810729,0.814109,0.816445,0.818432,...,0.839099,0.840326,0.841483,0.842070,0.842557,0.843133,0.843532,0.843641,0.844079,0.844610
0.9,0.742987,0.771137,0.784672,0.794646,0.801547,0.806084,0.809763,0.812730,0.815246,0.817744,...,0.834427,0.835668,0.837130,0.838176,0.839057,0.839980,0.840897,0.841811,0.843408,0.843961
1.0,0.854564,0.845447,0.834753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
px.imshow(df, aspect='auto')